host: stage.thoth-station.ninja
tls_verify: false

requirements_format: pipenv

runtime_environments:
  - name: "my_project"
    recommendation_type: LATEST
    operating_system:
      name: "rhel"
      version: "8.0"