host: khemenu.thoth-station.ninja
tls_verify: true

requirements_format: pipenv

runtime_environments:
  - name: "my_project"
    recommendation_type: latest
    operating_system:
      name: "rhel"
      version: "8.0"