- project:
    check:
      jobs:
        - thoth-pipenv-pytest
    gate:
      jobs:
        - noop

    release:
      jobs:
        - upload-test-pypi

    kebechet-auto-gate:
      jobs:
        - noop

- job:
    name: thoth-pipenv-pytest
    parent: base-openshift-pod
    nodeset:
      nodes:
        - name: pod
          label: linter-pod
          # FIXME there should be a seperate pod for pytest
    run: pytest.yaml
