- project:
    check:
      jobs:
        - thoth-coala
        - thoth-pytest
        - thoth-pylint
    gate:
      jobs:
        - noop

    release:
      jobs:
        - upload-test-pypi

    kebechet-auto-gate:
      jobs:
        - noop
